import { getEquipments, getEquipmentsFromDesk, getEquipment, addEquipment, updateEquipment, deleteEquipment, getEquipmentsWithName, getDistinctEquipments, getDistinctEquipmentsCount, getEquipmentsSeperated } from './equipments.js'
import { getDesks, getDesksFromLab, getDesk, addDesk, updateDesk, deleteDesk, getDesksSeparated } from './desks.js'
import { getLabs, getLab, addLab, updateLab, deleteLab } from './labs.js'
import { getReservations, getReservation, getUserReservations, getEquipmentReservations, getDeskReservations, addReservation, updateReservation, cancelReservation, deleteReservation } from './reservations.js'
import { getSpaces, getSpace, addSpace, updateSpace, deleteSpace } from './spaces.js'
import { getIssues, getIssue, getEquipmentIssues, getDeskIssues, getUserIssues, getLabIssues, addIssue, updateIssue, verifyIssue, resolveIssue, deleteIssue } from './issues.js'
import { getUsers, getUser, addUser, updateUser, deleteUser, changeScore, getUsersMaxId } from './users.js'

export default {
    getEquipments,
    getEquipmentsFromDesk,
    getEquipment,
    addEquipment,
    updateEquipment,
    deleteEquipment,
    getEquipmentsWithName,
    getDistinctEquipments,
    getDistinctEquipmentsCount,
    getEquipmentsSeperated,
    getDesks,
    getDesksFromLab,
    getDesk,
    addDesk,
    updateDesk,
    deleteDesk,
    getDesksSeparated,
    getLabs,
    getLab,
    addLab,
    updateLab,
    deleteLab,
    getReservations,
    getReservation,
    getUserReservations,
    getEquipmentReservations,
    getDeskReservations,
    addReservation,
    updateReservation,
    cancelReservation,
    deleteReservation,
    getSpaces,
    getSpace,
    addSpace,
    updateSpace,
    deleteSpace,
    getUsers,
    getUser,
    addUser,
    updateUser,
    deleteUser,
    changeScore,
    getUsersMaxId,
    getIssues,
    getIssue,
    getEquipmentIssues,
    getDeskIssues,
    getUserIssues,
    getLabIssues,
    addIssue,
    updateIssue,
    verifyIssue,
    resolveIssue,
    deleteIssue
}
